services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: wKJxPABOyrXQySLiLyr
      POSTGRES_PASSWORD: TirLRkNjXHHw
      POSTGRES_DB: college
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: developer@spfc.kr.ua
      PGADMIN_DEFAULT_PASSWORD: jDMHlQGfDOgE
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./pgadmin:/var/lib/pgadmin