"""005: add users.is_main_administrator field

Revision ID: 09b1cf972f94
Revises: 755224ffd3ae
Create Date: 2025-04-05 18:28:04.641975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09b1cf972f94'
down_revision: Union[str, None] = '755224ffd3ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_main_administrator', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_main_administrator')
    # ### end Alembic commands ###
