"""001: add headers models

Revision ID: db4db080a31b
Revises: 
Create Date: 2025-02-13 19:18:34.671577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db4db080a31b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header_name', sa.String(length=100), nullable=False),
    sa.Column('header_url', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('header_name')
    )
    op.create_table('header_tabs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header_id', sa.Integer(), nullable=False),
    sa.Column('tab_name', sa.String(length=100), nullable=False),
    sa.Column('tab_url', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['header_id'], ['headers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_header_tabs_header_id'), 'header_tabs', ['header_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_header_tabs_header_id'), table_name='header_tabs')
    op.drop_table('header_tabs')
    op.drop_table('headers')
    # ### end Alembic commands ###
