"""002: add pages models

Revision ID: e6ee8eb8110e
Revises: db4db080a31b
Create Date: 2025-03-31 20:37:12.650293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6ee8eb8110e'
down_revision: Union[str, None] = 'db4db080a31b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages',
    sa.Column('url', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('url')
    )
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_url', sa.String(length=32), nullable=False),
    sa.Column('block_id', sa.String(length=5), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('IMAGE', 'TEXT', 'VIDEO', name='blocktypeenum'), nullable=False),
    sa.ForeignKeyConstraint(['page_url'], ['pages.url'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocks_page_url'), 'blocks', ['page_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blocks_page_url'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_table('pages')
    # ### end Alembic commands ###
